// react/src/app/builder/builder.tsx
import { IgrAvatar, IgrAvatarModule, IgrList, IgrListItem, IgrListModule } from 'igniteui-react';
import { useEffect, useRef, useState } from 'react';
import styles from './builder.module.css';
import createClassTransformer from '../style-utils';
import { RevealViewOptions, VisualizationViewerOptions, SavingArgs, MenuOpeningArgs } from 'reveal-sdk-wrappers';
import { RvRevealView, RvRevealViewRef, RvVisualizationViewer } from 'reveal-sdk-wrappers-react';
import { RdashDocument } from '@revealbi/dom';

declare var $: any;

IgrAvatarModule.register();
IgrListModule.register();

export interface VisualizationChartInfo {
  dashboardFileName: string;
  dashboardTitle: string;
  vizId: string;
  vizTitle: string;
  vizChartType: string;
  selected: any;
}

export default function Builder() {
  const classes = createClassTransformer(styles);
  const uuid = () => crypto.randomUUID();
  const [visualizationId, setVisualizationId] = useState<string | undefined>();
  const [dashboardFileName, setDashboardFileName] = useState<string | undefined>();
  const [dashboardTitle, setDashboardTitle] = useState<string | undefined>();
  const [dashboardDocument, setDashboardDocument] = useState<RdashDocument | null>(null);
  const [selectedVisualizations, setSelectedVisualizations] = useState<VisualizationChartInfo[]>([]);
  const [sourceDocs, setSourceDocs] = useState(new Map());
  const [localVisualizationChartInfo, setLocalVisualizationChartInfo] = useState<VisualizationChartInfo[]>([]);
  const rvRef = useRef<RvRevealViewRef>(null);

  //const BASE_URL = "https://localhost:7219";
  const BASE_URL = "https://acmeanalyticsserver.azurewebsites.net/";


  const dashboardDocumentRef = useRef(dashboardDocument);
  dashboardDocumentRef.current = dashboardDocument;

  $.ig.RevealSdkSettings.setBaseUrl(BASE_URL);

  const singleVizOptions: VisualizationViewerOptions = {};
  const dashboardOptions: RevealViewOptions = {
    canEdit: true,
    canSaveAs: true,
    startInEditMode: true,
    dataSourceDialog: {
      showExistingDataSources: true,
    },
    header: {
      menu: {
        showMenu: true,
        exportToExcel: false,
        exportToPdf: false,
        exportToPowerPoint: false,
        exportToImage: false,
        refresh: false,
        items: [
          {
            icon: `https://raw.githubusercontent.com/FortAwesome/Font-Awesome/refs/heads/6.x/svgs/regular/circle-check.svg`, // `${BASE_URL}/images/not-empty.svg`,
            title: "Clear / Reset",
            click: () => resetDashboard(),
          },
        ],
      },
    },
  };

  // Fetch visualization data
  const getVisualizationChartInfoList = async (): Promise<VisualizationChartInfo[]> => {
    try {
      const response = await fetch(`${BASE_URL}/dashboards/visualizations`);
      if (!response.ok) {
        throw new Error(`HTTP error! Status: ${response.status}`);
      }
      const data = await response.json();
      return data;
    } catch (error) {
      console.error("Error fetching visualization chart info list:", error);
      return [];
    }
  };

  useEffect(() => {
    const fetchData = async () => {
      const visualizations = await getVisualizationChartInfoList();
      setLocalVisualizationChartInfo(visualizations);
    };
    fetchData();
  }, []);

  useEffect(() => {
    if (dashboardFileName) {
      console.log("Dashboard file name updated:", dashboardFileName);
    }
  }, [dashboardFileName]);

  const addVisualization = (
    viz: VisualizationChartInfo,
    event: React.MouseEvent<SVGSVGElement, MouseEvent>
  ) => {
    event.stopPropagation();
    const exists = selectedVisualizations.some(
      (selectedViz) =>
        selectedViz.vizId === viz.vizId && selectedViz.dashboardFileName === viz.dashboardFileName
    );
    if (exists) {
      alert("Visualization already in dashboard");
      return;
    }
    setSelectedVisualizations((prev) => [
      ...prev,
      { ...viz, selected: true },
    ]);
  };

  useEffect(() => {
    if (selectedVisualizations.length > 0) {
      generateDashboard();
    }
  }, [selectedVisualizations]);

  const generateDashboard = async () => {
    const document = new RdashDocument("Generated Dashboard");
    for (const viz of selectedVisualizations) {
      let sourceDoc = sourceDocs.get(viz.dashboardFileName);
      if (!sourceDoc) {
        try {
          sourceDoc = await RdashDocument.load(viz.dashboardFileName);
          setSourceDocs((prev) => new Map(prev).set(viz.dashboardFileName, sourceDoc));
        } catch (error) {
          console.error(`Failed to load document: ${viz.dashboardFileName}`, error);
          continue;
        }
      }
      if (sourceDoc) {
        document.import(sourceDoc, viz.vizId);
      }
    }
    if (JSON.stringify(document) !== JSON.stringify(dashboardDocumentRef.current)) {
      setDashboardDocument(document);
    }
  };

  const resetDashboard = () => {
    setSelectedVisualizations([]);
    setDashboardDocument(null);
  };

  const isDuplicateName = async (name: string) => {
    try {
      const response = await fetch(`${BASE_URL}/dashboards/${name}/exists`);
      if (!response.ok) {
        throw new Error(`HTTP error! Status: ${response.status}`);
      }
      const responseData = await response.json();
      return responseData;
    } catch (error) {
      console.error("Error checking duplicate name:", error);
      return false;
    }
  };

  const toggleSelected = (selectedItem: VisualizationChartInfo) => {
    setLocalVisualizationChartInfo((prevItems) =>
      prevItems.map((item) => ({
        ...item,
        selected:
          item.vizId === selectedItem.vizId &&
          item.vizTitle === selectedItem.vizTitle &&
          item.vizChartType === selectedItem.vizChartType &&
          item.dashboardTitle === selectedItem.dashboardTitle &&
          item.dashboardFileName === selectedItem.dashboardFileName,
      }))
    );
  };
  
  const saveDashboard = async (e: SavingArgs) => {
    const isInvalidName = (name: string) => {
      const invalidNames = ["generated dashboard", "new dashboard", ""];
      return invalidNames.includes(name.trim().toLowerCase());
    };

    let duplicate = await isDuplicateName(e.name);

    if (duplicate && !window.confirm(`A dashboard with name: ${e.name} already exists. Do you want to override it?`)) {
      return;
    }

    if (e.saveAs || isInvalidName(e.name)) {
      let newName: string | null = null;

      do {
        newName = window.prompt("Please enter a valid dashboard name");
        if (newName === null) {
          return;
        }

        duplicate = await isDuplicateName(newName);

        if (duplicate) {
          alert(`A dashboard with name: ${newName} already exists. Please enter a different name.`);
        } else if (isInvalidName(newName)) {
          alert("The name is not allowed. Please choose a different name.");
        }
      } while (isInvalidName(newName) || duplicate);
      e.dashboardId = e.name = newName;
    }

    e.saveFinished();
    resetDashboard();
    setTimeout(async () => {
      const updatedVisualizations = await getVisualizationChartInfoList();
      setLocalVisualizationChartInfo(updatedVisualizations);
    }, 2000);
  };

  const menuOpening = (args: MenuOpeningArgs) => {
    if (args.visualization) {
      args.menuItems[6].isHidden = true; 
      const newDeleteButton = new $.ig.RVMenuItem("Delete", "https://raw.githubusercontent.com/FortAwesome/Font-Awesome/refs/heads/6.x/svgs/regular/trash-can.svg", () => {      
        // Remove the visualization from selectedVisualizations so generateDashboard won't re-add it
        setSelectedVisualizations((prev) =>
          prev.filter((viz) => viz.vizId !== args.visualization.id)
        );
        // Also remove the widget from the currently displayed dashboard
        (rvRef.current as any)?._revealView._dashboardView.deleteWidgetFromDashboard(args.visualization._widgetModel);
      });
      args.menuItems.push(newDeleteButton);
    }
  }

  return (
    <>
      <div className={classes("row-layout builder-container")}>
        <div className={classes("column-layout group")}>
          <div className={classes("row-layout group_1")}>
            <IgrList className={classes("list")}>
              {localVisualizationChartInfo.map((item) => (
                <div
                  style={{ display: "contents" }}
                  onClick={() => setVisualizationId(item.vizId)}
                  key={uuid()}
                >
                  <IgrListItem
                    key={item.vizId}
                    selected={item.selected ? true : undefined}
                    onClick={() => {
                      setDashboardFileName(item.dashboardFileName);
                      setDashboardTitle(item.dashboardTitle);
                      toggleSelected(item);
                    }}
                  >
                    <div slot="start" key={uuid()}>
                      <IgrAvatar
                        shape="circle"
                        className={classes("avatar")}
                        style={{
                          backgroundImage: `url('${BASE_URL}/images/png/${item.vizChartType}.png')`,
                          backgroundSize: "cover",
                        }}
                        key={uuid()}
                      ></IgrAvatar>
                    </div>
                    <div slot="title" key={uuid()}>
                      {item.vizTitle}
                    </div>
                    <div slot="subtitle" key={uuid()}>
                      {item.dashboardTitle}
                    </div>
                    <span
                      slot="end"
                      onClick={(event: any) => {
                        event.stopPropagation();
                        addVisualization(item, event);
                        setDashboardFileName(item.dashboardFileName);
                        setDashboardTitle(item.dashboardTitle);
                        toggleSelected(item);
                      }}
                      className={classes("material-icons icon")}
                      key={uuid()}
                    >
                      <span key={uuid()}>add_photo_alternate</span>
                    </span>
                  </IgrListItem>
                </div>
              ))}
            </IgrList>
          </div>
          <div className={classes("group_2")}>
            <RvVisualizationViewer
              dashboard={dashboardFileName!}
              visualization={visualizationId!}
              options={singleVizOptions}
            ></RvVisualizationViewer>
          </div>
        </div>
        <div className={classes("column-layout group_3")}>
          <div className={classes("row-layout group_4")}>
            <div className={classes("group_2")}>
              <RvRevealView ref={rvRef} 
                dashboard={dashboardDocument}
                options={dashboardOptions}
                saving={saveDashboard}
                menuOpening={menuOpening}
              ></RvRevealView>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

// angular/src/app/builder/builder.component.ts
import { NgFor } from '@angular/common';
import { CommonModule } from '@angular/common';
import { AfterViewInit, Component, ElementRef, OnDestroy, OnInit, ViewChild } from '@angular/core';
import { IGX_LIST_DIRECTIVES, IgxAvatarComponent, IgxIconComponent } from 'igniteui-angular';
import { Subject, takeUntil } from 'rxjs';
import { VisualizationChartInfo } from '../models/reveal-server/visualization-chart-info';
import { RevealServerService } from '../services/reveal-server.service';
import { environment } from '../../environments/environment';
import { RdashDocument } from '@revealbi/dom';

declare let $: any;

@Component({
  selector: 'app-builder',
  standalone: true,
  imports: [CommonModule, IGX_LIST_DIRECTIVES, IgxAvatarComponent, IgxIconComponent, NgFor],
  templateUrl: './builder.component.html',
  styleUrls: ['./builder.component.scss']
})
export class BuilderComponent implements OnInit, OnDestroy {
 
  private destroy$: Subject<void> = new Subject<void>();
  public visualizationId?: string;
  public selectedVisualization?: VisualizationChartInfo;
  public revealServerVisualizationChartInfo: VisualizationChartInfo[] = [];


  // Variables for Generate Dashboard
  dashboardDocument: RdashDocument | string | null = "";
  vizCollection: VisualizationChartInfo[] = [];
  sourceDocs: Map<string, RdashDocument> = new Map();

  // Correctly reference the revealSingleViz and revealDashboard elements
  @ViewChild('revealSingleViz') public revealSingleViz!: ElementRef;
  @ViewChild('revealDashboard') public revealDashboard!: ElementRef;

  // variables to store the revealView and dashboard in the listItemClick method
  public revealView: any;
  public dashboard: any;

  // add the envornment variable for use in the HTML to set the IMAGE_URL
  public environment = environment;

  // Add a variable to store the selected item in the listItemClick method
  prevSelected: any;
  dashboard1: any;
  revealView1: any;

  constructor(
    private revealServerService: RevealServerService,
  ) {}

  ngOnInit() {
      this.loadVisualizationChartInfo();
    }
    

  loadVisualizationChartInfo() {
    this.revealServerService.getVisualizationChartInfoList().pipe(takeUntil(this.destroy$)).subscribe({
      next: (data) => {
        this.revealServerVisualizationChartInfo = data;
        // Add this to select the first item in the list when the page loads
        if (this.revealServerVisualizationChartInfo.length > 0) {
          setTimeout(() => this.listItemClick(this.revealServerVisualizationChartInfo[0]), 0);
        }
      },
      error: (_err: any) => this.revealServerVisualizationChartInfo = []
    });
  }

  ngOnDestroy() {
    this.destroy$.next();
    this.destroy$.complete();
  }

  // Get the item.visualizationID and Filename to load the single visualization
  public async listItemClick(item: VisualizationChartInfo) {
   if (this.prevSelected) {
      this.prevSelected.selected = false;
    }
      item.selected = true;
      this.prevSelected = item;

    this.selectedVisualization = item;

    this.dashboard = await $.ig.RVDashboard.loadDashboard(item.dashboardFileName);
    this.revealView = new $.ig.RevealView(this.revealSingleViz.nativeElement);
    this.revealView.dashboard = this.dashboard;
    this.revealView.singleVisualizationMode = true;
    this.revealView.maximizedVisualization = this.dashboard.visualizations.getById(item.vizId);
  }

    public iconClick(item: VisualizationChartInfo, event: MouseEvent) {    
      // Call stopPropagation to prevent the event from bubbling up the DOM tree
      event.stopPropagation();
    
      // Check if the item clicked is different from the currently selected item
      if (!this.selectedVisualization || this.selectedVisualization.vizId !== item.vizId) {
        console.log("Item Clicked:", item);
        this.listItemClick(item);
      }
    
      if (this.selectedVisualization) {
        // Check if the visualization already exists in the collection
        const exists = this.vizCollection.some(
          (viz) => viz.vizId === this.selectedVisualization!.vizId
        );
    
        if (exists) {
          // Display an error message
          alert("Visualization already in dashboard");
          return;
        }
    
        // Add the visualization if it does not already exist
        this.vizCollection.push(this.selectedVisualization);
        this.generateDashboard();
      } else {
        console.error('Selected visualization is undefined');
      }
    }
  

  // public iconClick(item: VisualizationChartInfo, event: MouseEvent) {    
  //   // call stopPropagation to prevent the event from bubbling up the DOM tree
  //   event.stopPropagation();

  //   // Check if the item clicked is different from the currently selected item
  //   if (!this.selectedVisualization || this.selectedVisualization.vizId!== item.vizId) {
  //     console.log("Item Clicked:", item);
  //     this.listItemClick(item);
  //   }

  //   if (this.selectedVisualization) {
  //     this.vizCollection.push(this.selectedVisualization);
  //     this.generateDashboard();
  //   } else {
  //     console.error('Selected visualization is undefined');
  //   }
  // }
  
  private async generateDashboard(): Promise<void> {
    console.log("Add Generated Dashboard");
    const document = new RdashDocument("Generated Dashboard");
    for (const viz of this.vizCollection) {
      let sourceDoc = this.sourceDocs.get(viz.dashboardFileName);
      if (!sourceDoc) {
        try {
          sourceDoc = await RdashDocument.load(viz.dashboardFileName);
          this.sourceDocs.set(viz.dashboardFileName, sourceDoc);
        } catch (error) {
          console.error(`Failed to load document: ${viz.dashboardFileName}`, error);
          continue;
        }
      }
      if (sourceDoc) {
        document.import(sourceDoc, viz.vizId);
      }
    }
    if (!this.dashboardDocument) { 
      this.setupRevealView();
    }    
    this.revealView1.dashboard = await document.toRVDashboard();
  }

  private setupRevealView() {
    this.revealView1 = new $.ig.RevealView(this.revealDashboard.nativeElement);
    this.revealView1.hoverTooltipsEnabled = true;
    this.revealView1.interactiveFilteringEnabled = true;
    this.revealView1.startInEditMode = true;
  
    this.revealView1.onSave = async (rv: any, args: any) => {
      console.log("Save event triggered");
      const isInvalidName = (name: string) => {
        return name === "Generated Dashboard" || name === "New Dashboard" || name === "";
    };

    console.log("Dashboard Name: " + args.name);
    console.log("Dashboard Id: " + args.dashboardId)

    if (args.saveAs || isInvalidName(args.name)) {
      let newName: string | null;
        do {
            newName = prompt("Please enter a valid dashboard name");
            if (newName === null) {
                return; 
            }
        } while (isInvalidName(newName)); 

        this.isDuplicateName(newName).then(isDuplicate => {
            if (isDuplicate === 'true') {
                if (!window.confirm("A dashboard with name: " + newName + " already exists. Do you want to override it?")) {
                    return; 
                }
            }
            args.dashboardId = args.name = newName!;
            args.saveFinished();
            setTimeout(() => {this.loadVisualizationChartInfo(); }, 2000);
        });
    } else {
      args.saveFinished(); 
      setTimeout(() => {this.loadVisualizationChartInfo(); }, 2000);
    }
  };

    this.revealView1.onMenuOpening = (rv: any, args: any) => {
      console.log("Menu opening event triggered");
      if (args.menuLocation === $.ig.RVMenuLocation.Dashboard) {
      
        // Hide Export options
        for (let i = 0; i < args.menuItems.length; i++) {
          if(args.menuItems[i].title === "Export") args.menuItems[i].isHidden = true;
        }

        const menuItem = new $.ig.RVMenuItem("Clear / Reset", 
              new $.ig.RVImage(environment.IMAGE_URL + "custom.png", "Icon"), () => {
                this.resetDashboard();
            })
            args.menuItems.push(menuItem);
      }
    };
  }

  private isDuplicateName(name: string): Promise<string> {
    return fetch(`${environment.BASE_URL}/dashboards/${name}/exists`).then(resp => resp.text());
  }

  resetDashboard() {
    this.vizCollection = [];
    this.dashboardDocument = null;
    this.revealView1.dashboard = null;
  }
}
